### ISSUE TITLE
xcollector should be able to auto-recover from write endpoint failures

### ISSUE THREAD

**Issue by talonx** [ApptuitAI/xcollector#58]
If the write endpoint is down for a certain amount of time, xcollector dies and has to be restarted manually.

**Comment by rshivane** [comment]
http://heyman.info/2010/apr/22/python-urllib2-timeout-issue/

Since Python 2.6, urllib2 provides a way to set the timeout time.   

If no timeout is specified, the global socket timeout value will be used, which by default is infinite.

**Comment by rshivane** [comment]
Fixed in #60
